/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.example;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class StringList extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StringList\",\"namespace\":\"org.example\",\"fields\":[{\"name\":\"value\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<java.lang.CharSequence> value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public StringList() {}

  /**
   * All-args constructor.
   */
  public StringList(java.util.List<java.lang.CharSequence> value) {
    this.value = value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: value = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'value' field.
   */
  public java.util.List<java.lang.CharSequence> getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.util.List<java.lang.CharSequence> value) {
    this.value = value;
  }

  /** Creates a new StringList RecordBuilder */
  public static org.example.StringList.Builder newBuilder() {
    return new org.example.StringList.Builder();
  }
  
  /** Creates a new StringList RecordBuilder by copying an existing Builder */
  public static org.example.StringList.Builder newBuilder(org.example.StringList.Builder other) {
    return new org.example.StringList.Builder(other);
  }
  
  /** Creates a new StringList RecordBuilder by copying an existing StringList instance */
  public static org.example.StringList.Builder newBuilder(org.example.StringList other) {
    return new org.example.StringList.Builder(other);
  }
  
  /**
   * RecordBuilder for StringList instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StringList>
    implements org.apache.avro.data.RecordBuilder<StringList> {

    private java.util.List<java.lang.CharSequence> value;

    /** Creates a new Builder */
    private Builder() {
      super(org.example.StringList.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.example.StringList.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing StringList instance */
    private Builder(org.example.StringList other) {
            super(org.example.StringList.SCHEMA$);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'value' field */
    public java.util.List<java.lang.CharSequence> getValue() {
      return value;
    }
    
    /** Sets the value of the 'value' field */
    public org.example.StringList.Builder setValue(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[0], value);
      this.value = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'value' field has been set */
    public boolean hasValue() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'value' field */
    public org.example.StringList.Builder clearValue() {
      value = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public StringList build() {
      try {
        StringList record = new StringList();
        record.value = fieldSetFlags()[0] ? this.value : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
